from selenium.webdriver.common.by import By


class HomeWebElements:
    where_label = (By.CLASS_NAME, 'main-logo__link')
    signin_button = (By.XPATH, '//span[text()="Iniciar sesión" or text()="Sign in" or text()="Entrar"]')
    search_button = (
    By.CSS_SELECTOR, '.pageContent .SearchPage__FrontDoor .HPw7-form-fields-and-submit .HPw7-submit button')
    search_tag_div = (By.XPATH, '(//button[@aria-label="Search" or @aria-label="Buscar"]//div)[last()]')
    city_search_input = (By.XPATH, '//div[@id="main-search-form"]//input')
    flight_option_a = (By.XPATH, '//div[contains(@class,"nav-items")]//a')
    header_welcome = (By.CLASS_NAME, 'header-welcome')
    menu_present = (By.CLASS_NAME, 'HtHs-nav-list')
    flights_h2 = (By.XPATH, '//h2[contains(text(),"Busca en cientos de webs de vuelos a la vez")]')
    accommodation_option_div = (By.XPATH, '//div[contains(text(),"Alojamientos")]')
    accommodation_h2 = (By.XPATH, '//h2[text()="Busca el alojamiento perfecto para ti."]')
    car_option_a = (By.CSS_SELECTOR, 'a.dJtn[href="/cars"]')
    car_a = (By.XPATH, '//a[@aria-label="Buscar autos "]')
    packages_option_a = (By.CSS_SELECTOR, 'a[aria-label="Buscar vacaciones "]')
    packages_h1 = (By.CSS_SELECTOR, '.title-section .title.dark')
    explorer_option_a = (By.CSS_SELECTOR, 'a.dJtn.dJtn-expanded.dJtn-mod-variant-accordion[aria-label="Ir a Explore "]')
    explorer_div = (By.XPATH, '//div[@class="header-title" and text()="Explora destinos"]')
    blog_option_a = (By.CSS_SELECTOR, 'a.dJtn[href="#"][aria-label="Visita nuestro blog "]')
    blog_a = (By.CSS_SELECTOR, 'a.non-accordion-link[href="https://www.kayak.com.co/news/category/recomendaciones-de-viaje/"]')
    flight_direct_option_div = (By.XPATH, '//div[contains(text(), "Vuelos directos")]')
    flight_direct_h2 = (By.XPATH, '//h2[contains(text(), "Vuelos directos desde Bogotá, Colombia - El Dorado (BOG)")]')
    best_moment_option_div = (By.XPATH, '//div[text()="El mejor momento"]')
    best_moment_h1 = (By.XPATH, '//h1[@class="lyx0-header"]')
    business_option_div = (By.XPATH, '//div[contains(text(), "KAYAK for Business")]')
    business_button = (By.XPATH, '//button[contains(., "Registrarse")]')
    trips_option_a = (By.XPATH, '//a[contains(@class, "dJtn") and contains(@aria-label, "Trips")]')
    trips_h1 = (By.CLASS_NAME, 'c7Ucr-hero-block__title')
    language_option_div = (By.XPATH, '//div[contains(@class, "dJtn")][contains(@aria-label, "Español")]')
    language_span = (By.XPATH, '//span[@class="c8nDX-label" and text()="Argentina"]')
    validate_search_div=(By.XPATH, '//div[@class="TaO3-info-text" and text()="Selecciona un aeropuerto en la página de búsqueda"]')
    signin_validate_div = (By.XPATH, '//div[@class="header-welcome" and text()="Iniciar sesión o crear una cuenta"]')
    search_click_div = (By.XPATH, '//div[@class="RxNS-button-container"]')
